# Generated by Django 2.1.4 on 2019-02-18 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_auto_20190108_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapply',
            name='act_exp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='high_qual',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='marital',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='total_exp',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='jobapply',
            name='year_of_qual',
            field=models.CharField(max_length=50),
        ),
    ]
